// AUTO-GENERATED by scripts/gen-types.mjs — do not edit by hand.
// Regenerate after every migration:  node scripts/gen-types.mjs

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      account_credits: {
        Row: {
          id: string;
          user_id: string;
          amount: number;
          currency: string;
          reason: string | null;
          granted_by: string | null;
          expires_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          amount: number;
          currency?: string;
          reason?: string | null;
          granted_by?: string | null;
          expires_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          amount?: number;
          currency?: string;
          reason?: string | null;
          granted_by?: string | null;
          expires_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "account_credits_granted_by_fkey";
            columns: ["granted_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "account_credits_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      account_discounts: {
        Row: {
          id: string;
          user_id: string;
          percent: number;
          reason: string | null;
          granted_by: string | null;
          is_active: boolean;
          expires_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          percent: number;
          reason?: string | null;
          granted_by?: string | null;
          is_active?: boolean;
          expires_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          percent?: number;
          reason?: string | null;
          granted_by?: string | null;
          is_active?: boolean;
          expires_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "account_discounts_granted_by_fkey";
            columns: ["granted_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "account_discounts_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      audit_log: {
        Row: {
          id: number;
          actor_id: string | null;
          actor_role: Database["public"]["Enums"]["user_role"] | null;
          action: string;
          entity_type: string;
          entity_id: string | null;
          summary: string | null;
          before: Json | null;
          after: Json | null;
          created_at: string;
        };
        Insert: {
          id?: number;
          actor_id?: string | null;
          actor_role?: Database["public"]["Enums"]["user_role"] | null;
          action: string;
          entity_type: string;
          entity_id?: string | null;
          summary?: string | null;
          before?: Json | null;
          after?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: number;
          actor_id?: string | null;
          actor_role?: Database["public"]["Enums"]["user_role"] | null;
          action?: string;
          entity_type?: string;
          entity_id?: string | null;
          summary?: string | null;
          before?: Json | null;
          after?: Json | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "audit_log_actor_id_fkey";
            columns: ["actor_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      custom_questions: {
        Row: {
          id: string;
          event_id: string;
          label: string;
          help_text: string | null;
          type: Database["public"]["Enums"]["question_type"];
          options: Json;
          is_required: boolean;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          event_id: string;
          label: string;
          help_text?: string | null;
          type: Database["public"]["Enums"]["question_type"];
          options?: Json;
          is_required?: boolean;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          event_id?: string;
          label?: string;
          help_text?: string | null;
          type?: Database["public"]["Enums"]["question_type"];
          options?: Json;
          is_required?: boolean;
          sort_order?: number;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "custom_questions_event_id_fkey";
            columns: ["event_id"];
            isOneToOne: false;
            referencedRelation: "events";
            referencedColumns: ["id"];
          },
        ];
      };
      event_admin_assignments: {
        Row: {
          event_id: string;
          user_id: string;
          assigned_by: string | null;
          assigned_at: string;
        };
        Insert: {
          event_id: string;
          user_id: string;
          assigned_by?: string | null;
          assigned_at?: string;
        };
        Update: {
          event_id?: string;
          user_id?: string;
          assigned_by?: string | null;
          assigned_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "event_admin_assignments_assigned_by_fkey";
            columns: ["assigned_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "event_admin_assignments_event_id_fkey";
            columns: ["event_id"];
            isOneToOne: false;
            referencedRelation: "events";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "event_admin_assignments_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      event_admin_permissions: {
        Row: {
          user_id: string;
          permission: string;
          granted_by: string | null;
          granted_at: string;
        };
        Insert: {
          user_id: string;
          permission: string;
          granted_by?: string | null;
          granted_at?: string;
        };
        Update: {
          user_id?: string;
          permission?: string;
          granted_by?: string | null;
          granted_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "event_admin_permissions_granted_by_fkey";
            columns: ["granted_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "event_admin_permissions_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      event_admin_profiles: {
        Row: {
          user_id: string;
          organization_id: string | null;
          title: string | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          user_id: string;
          organization_id?: string | null;
          title?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          user_id?: string;
          organization_id?: string | null;
          title?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "event_admin_profiles_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "event_admin_profiles_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "event_admin_profiles_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: true;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      event_config: {
        Row: {
          event_id: string;
          max_participants: number | null;
          min_participants: number;
          waitlist_capacity: number;
          min_age: number | null;
          max_age: number | null;
          gender_requirement: Database["public"]["Enums"]["gender_requirement"];
          skill_levels: string[];
          team_size: number | null;
          max_teams: number | null;
          substitutes_per_team: number;
          allow_individual_join: boolean;
        };
        Insert: {
          event_id: string;
          max_participants?: number | null;
          min_participants?: number;
          waitlist_capacity?: number;
          min_age?: number | null;
          max_age?: number | null;
          gender_requirement?: Database["public"]["Enums"]["gender_requirement"];
          skill_levels?: string[];
          team_size?: number | null;
          max_teams?: number | null;
          substitutes_per_team?: number;
          allow_individual_join?: boolean;
        };
        Update: {
          event_id?: string;
          max_participants?: number | null;
          min_participants?: number;
          waitlist_capacity?: number;
          min_age?: number | null;
          max_age?: number | null;
          gender_requirement?: Database["public"]["Enums"]["gender_requirement"];
          skill_levels?: string[];
          team_size?: number | null;
          max_teams?: number | null;
          substitutes_per_team?: number;
          allow_individual_join?: boolean;
        };
        Relationships: [
          {
            foreignKeyName: "event_config_event_id_fkey";
            columns: ["event_id"];
            isOneToOne: true;
            referencedRelation: "events";
            referencedColumns: ["id"];
          },
        ];
      };
      event_messages: {
        Row: {
          id: string;
          event_id: string;
          sender_id: string | null;
          audience: Database["public"]["Enums"]["message_audience"];
          subject: string;
          body: string;
          recipient_count: number;
          sent_at: string;
        };
        Insert: {
          id?: string;
          event_id: string;
          sender_id?: string | null;
          audience?: Database["public"]["Enums"]["message_audience"];
          subject: string;
          body: string;
          recipient_count?: number;
          sent_at?: string;
        };
        Update: {
          id?: string;
          event_id?: string;
          sender_id?: string | null;
          audience?: Database["public"]["Enums"]["message_audience"];
          subject?: string;
          body?: string;
          recipient_count?: number;
          sent_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "event_messages_event_id_fkey";
            columns: ["event_id"];
            isOneToOne: false;
            referencedRelation: "events";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "event_messages_sender_id_fkey";
            columns: ["sender_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      events: {
        Row: {
          id: string;
          slug: string;
          name: string;
          sport_id: string;
          format_id: string | null;
          description: string;
          organizer_id: string;
          organization_id: string | null;
          banner_url: string | null;
          gallery: Json;
          venue_id: string | null;
          venue_name: string | null;
          venue_address: string | null;
          latitude: number | null;
          longitude: number | null;
          starts_at: string;
          ends_at: string | null;
          registration_opens_at: string | null;
          registration_closes_at: string | null;
          timezone: string;
          rules: string | null;
          eligibility: string | null;
          whats_included: string[];
          participant_requirements: string | null;
          cancellation_policy: string | null;
          sponsors: Json;
          contact_name: string | null;
          contact_email: string | null;
          contact_phone: string | null;
          terms: string | null;
          registration_model: Database["public"]["Enums"]["registration_model"];
          price_amount: number;
          currency: string;
          price_unit: string;
          tax_percent: number;
          status: Database["public"]["Enums"]["event_status"];
          is_featured: boolean;
          submitted_at: string | null;
          reviewed_at: string | null;
          reviewed_by: string | null;
          review_note: string | null;
          published_at: string | null;
          cancelled_at: string | null;
          cancellation_reason: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          sport_id: string;
          format_id?: string | null;
          description?: string;
          organizer_id: string;
          organization_id?: string | null;
          banner_url?: string | null;
          gallery?: Json;
          venue_id?: string | null;
          venue_name?: string | null;
          venue_address?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          starts_at: string;
          ends_at?: string | null;
          registration_opens_at?: string | null;
          registration_closes_at?: string | null;
          timezone?: string;
          rules?: string | null;
          eligibility?: string | null;
          whats_included?: string[];
          participant_requirements?: string | null;
          cancellation_policy?: string | null;
          sponsors?: Json;
          contact_name?: string | null;
          contact_email?: string | null;
          contact_phone?: string | null;
          terms?: string | null;
          registration_model?: Database["public"]["Enums"]["registration_model"];
          price_amount?: number;
          currency?: string;
          price_unit?: string;
          tax_percent?: number;
          status?: Database["public"]["Enums"]["event_status"];
          is_featured?: boolean;
          submitted_at?: string | null;
          reviewed_at?: string | null;
          reviewed_by?: string | null;
          review_note?: string | null;
          published_at?: string | null;
          cancelled_at?: string | null;
          cancellation_reason?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          sport_id?: string;
          format_id?: string | null;
          description?: string;
          organizer_id?: string;
          organization_id?: string | null;
          banner_url?: string | null;
          gallery?: Json;
          venue_id?: string | null;
          venue_name?: string | null;
          venue_address?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          starts_at?: string;
          ends_at?: string | null;
          registration_opens_at?: string | null;
          registration_closes_at?: string | null;
          timezone?: string;
          rules?: string | null;
          eligibility?: string | null;
          whats_included?: string[];
          participant_requirements?: string | null;
          cancellation_policy?: string | null;
          sponsors?: Json;
          contact_name?: string | null;
          contact_email?: string | null;
          contact_phone?: string | null;
          terms?: string | null;
          registration_model?: Database["public"]["Enums"]["registration_model"];
          price_amount?: number;
          currency?: string;
          price_unit?: string;
          tax_percent?: number;
          status?: Database["public"]["Enums"]["event_status"];
          is_featured?: boolean;
          submitted_at?: string | null;
          reviewed_at?: string | null;
          reviewed_by?: string | null;
          review_note?: string | null;
          published_at?: string | null;
          cancelled_at?: string | null;
          cancellation_reason?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "events_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "events_format_id_fkey";
            columns: ["format_id"];
            isOneToOne: false;
            referencedRelation: "sport_formats";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "events_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "events_organizer_id_fkey";
            columns: ["organizer_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "events_reviewed_by_fkey";
            columns: ["reviewed_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "events_sport_id_fkey";
            columns: ["sport_id"];
            isOneToOne: false;
            referencedRelation: "sports";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "events_venue_id_fkey";
            columns: ["venue_id"];
            isOneToOne: false;
            referencedRelation: "venues";
            referencedColumns: ["id"];
          },
        ];
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          type: string;
          title: string;
          body: string | null;
          link: string | null;
          read_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: string;
          title: string;
          body?: string | null;
          link?: string | null;
          read_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          type?: string;
          title?: string;
          body?: string | null;
          link?: string | null;
          read_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "notifications_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      organizations: {
        Row: {
          id: string;
          name: string;
          contact_email: string | null;
          contact_phone: string | null;
          logo_url: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          contact_email?: string | null;
          contact_phone?: string | null;
          logo_url?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          contact_email?: string | null;
          contact_phone?: string | null;
          logo_url?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      payments: {
        Row: {
          id: string;
          registration_id: string;
          event_id: string;
          reference_code: string;
          subtotal_amount: number;
          discount_amount: number;
          platform_fee_amount: number;
          tax_amount: number;
          total_amount: number;
          currency: string;
          method: Database["public"]["Enums"]["payment_method"];
          status: Database["public"]["Enums"]["payment_status"];
          payer_reference: string | null;
          proof_url: string | null;
          marked_paid_by: string | null;
          marked_paid_at: string | null;
          admin_note: string | null;
          gateway_transaction_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          registration_id: string;
          event_id: string;
          reference_code: string;
          subtotal_amount?: number;
          discount_amount?: number;
          platform_fee_amount?: number;
          tax_amount?: number;
          total_amount?: number;
          currency?: string;
          method: Database["public"]["Enums"]["payment_method"];
          status?: Database["public"]["Enums"]["payment_status"];
          payer_reference?: string | null;
          proof_url?: string | null;
          marked_paid_by?: string | null;
          marked_paid_at?: string | null;
          admin_note?: string | null;
          gateway_transaction_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          registration_id?: string;
          event_id?: string;
          reference_code?: string;
          subtotal_amount?: number;
          discount_amount?: number;
          platform_fee_amount?: number;
          tax_amount?: number;
          total_amount?: number;
          currency?: string;
          method?: Database["public"]["Enums"]["payment_method"];
          status?: Database["public"]["Enums"]["payment_status"];
          payer_reference?: string | null;
          proof_url?: string | null;
          marked_paid_by?: string | null;
          marked_paid_at?: string | null;
          admin_note?: string | null;
          gateway_transaction_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "payments_event_id_fkey";
            columns: ["event_id"];
            isOneToOne: false;
            referencedRelation: "events";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "payments_marked_paid_by_fkey";
            columns: ["marked_paid_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "payments_registration_id_fkey";
            columns: ["registration_id"];
            isOneToOne: true;
            referencedRelation: "registrations";
            referencedColumns: ["id"];
          },
        ];
      };
      platform_fee_config: {
        Row: {
          id: string;
          scope: string;
          sport_id: string | null;
          event_id: string | null;
          mode: Database["public"]["Enums"]["fee_mode"];
          fixed_amount: number;
          percentage: number;
          is_active: boolean;
          updated_by: string | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          scope: string;
          sport_id?: string | null;
          event_id?: string | null;
          mode?: Database["public"]["Enums"]["fee_mode"];
          fixed_amount?: number;
          percentage?: number;
          is_active?: boolean;
          updated_by?: string | null;
          updated_at?: string;
        };
        Update: {
          id?: string;
          scope?: string;
          sport_id?: string | null;
          event_id?: string | null;
          mode?: Database["public"]["Enums"]["fee_mode"];
          fixed_amount?: number;
          percentage?: number;
          is_active?: boolean;
          updated_by?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "platform_fee_config_event_id_fkey";
            columns: ["event_id"];
            isOneToOne: false;
            referencedRelation: "events";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "platform_fee_config_sport_id_fkey";
            columns: ["sport_id"];
            isOneToOne: false;
            referencedRelation: "sports";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "platform_fee_config_updated_by_fkey";
            columns: ["updated_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      platform_settings: {
        Row: {
          id: boolean;
          payment_methods_enabled: Database["public"]["Enums"]["payment_method"][];
          bank_account_name: string | null;
          bank_name: string | null;
          bank_iban: string | null;
          bank_swift: string | null;
          support_email: string | null;
          support_phone: string | null;
          default_currency: string;
          default_terms: string | null;
          default_cancellation_policy: string | null;
          updated_by: string | null;
          updated_at: string;
        };
        Insert: {
          id?: boolean;
          payment_methods_enabled?: Database["public"]["Enums"]["payment_method"][];
          bank_account_name?: string | null;
          bank_name?: string | null;
          bank_iban?: string | null;
          bank_swift?: string | null;
          support_email?: string | null;
          support_phone?: string | null;
          default_currency?: string;
          default_terms?: string | null;
          default_cancellation_policy?: string | null;
          updated_by?: string | null;
          updated_at?: string;
        };
        Update: {
          id?: boolean;
          payment_methods_enabled?: Database["public"]["Enums"]["payment_method"][];
          bank_account_name?: string | null;
          bank_name?: string | null;
          bank_iban?: string | null;
          bank_swift?: string | null;
          support_email?: string | null;
          support_phone?: string | null;
          default_currency?: string;
          default_terms?: string | null;
          default_cancellation_policy?: string | null;
          updated_by?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "platform_settings_updated_by_fkey";
            columns: ["updated_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      profiles: {
        Row: {
          id: string;
          role: Database["public"]["Enums"]["user_role"];
          status: Database["public"]["Enums"]["account_status"];
          full_name: string;
          email: string;
          phone: string | null;
          date_of_birth: string | null;
          gender: string | null;
          nationality: string | null;
          avatar_url: string | null;
          preferences: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          role?: Database["public"]["Enums"]["user_role"];
          status?: Database["public"]["Enums"]["account_status"];
          full_name?: string;
          email: string;
          phone?: string | null;
          date_of_birth?: string | null;
          gender?: string | null;
          nationality?: string | null;
          avatar_url?: string | null;
          preferences?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          role?: Database["public"]["Enums"]["user_role"];
          status?: Database["public"]["Enums"]["account_status"];
          full_name?: string;
          email?: string;
          phone?: string | null;
          date_of_birth?: string | null;
          gender?: string | null;
          nationality?: string | null;
          avatar_url?: string | null;
          preferences?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "profiles_id_fkey";
            columns: ["id"];
            isOneToOne: true;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      refunds: {
        Row: {
          id: string;
          payment_id: string;
          registration_id: string;
          amount: number;
          currency: string;
          type: Database["public"]["Enums"]["refund_type"];
          status: Database["public"]["Enums"]["refund_status"];
          reason: string | null;
          policy_applied: string | null;
          initiated_by: string | null;
          initiated_by_role: Database["public"]["Enums"]["user_role"] | null;
          decided_by: string | null;
          decided_at: string | null;
          processed_at: string | null;
          settlement_note: string | null;
          proof_url: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          payment_id: string;
          registration_id: string;
          amount?: number;
          currency?: string;
          type: Database["public"]["Enums"]["refund_type"];
          status?: Database["public"]["Enums"]["refund_status"];
          reason?: string | null;
          policy_applied?: string | null;
          initiated_by?: string | null;
          initiated_by_role?: Database["public"]["Enums"]["user_role"] | null;
          decided_by?: string | null;
          decided_at?: string | null;
          processed_at?: string | null;
          settlement_note?: string | null;
          proof_url?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          payment_id?: string;
          registration_id?: string;
          amount?: number;
          currency?: string;
          type?: Database["public"]["Enums"]["refund_type"];
          status?: Database["public"]["Enums"]["refund_status"];
          reason?: string | null;
          policy_applied?: string | null;
          initiated_by?: string | null;
          initiated_by_role?: Database["public"]["Enums"]["user_role"] | null;
          decided_by?: string | null;
          decided_at?: string | null;
          processed_at?: string | null;
          settlement_note?: string | null;
          proof_url?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "refunds_decided_by_fkey";
            columns: ["decided_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "refunds_initiated_by_fkey";
            columns: ["initiated_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "refunds_payment_id_fkey";
            columns: ["payment_id"];
            isOneToOne: false;
            referencedRelation: "payments";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "refunds_registration_id_fkey";
            columns: ["registration_id"];
            isOneToOne: false;
            referencedRelation: "registrations";
            referencedColumns: ["id"];
          },
        ];
      };
      registration_answers: {
        Row: {
          registration_id: string;
          question_id: string;
          value: Json;
        };
        Insert: {
          registration_id: string;
          question_id: string;
          value: Json;
        };
        Update: {
          registration_id?: string;
          question_id?: string;
          value?: Json;
        };
        Relationships: [
          {
            foreignKeyName: "registration_answers_question_id_fkey";
            columns: ["question_id"];
            isOneToOne: false;
            referencedRelation: "custom_questions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "registration_answers_registration_id_fkey";
            columns: ["registration_id"];
            isOneToOne: false;
            referencedRelation: "registrations";
            referencedColumns: ["id"];
          },
        ];
      };
      registrations: {
        Row: {
          id: string;
          event_id: string;
          user_id: string | null;
          team_id: string | null;
          participant_name: string;
          participant_email: string | null;
          participant_phone: string | null;
          role: Database["public"]["Enums"]["participant_role"];
          status: Database["public"]["Enums"]["registration_status"];
          source: Database["public"]["Enums"]["registration_source"];
          is_captain: boolean;
          waitlist_position: number | null;
          registered_at: string;
          confirmed_at: string | null;
          cancelled_at: string | null;
          cancellation_reason: string | null;
          cancelled_by: string | null;
          checked_in_at: string | null;
          notes: string | null;
          created_by: string | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          event_id: string;
          user_id?: string | null;
          team_id?: string | null;
          participant_name: string;
          participant_email?: string | null;
          participant_phone?: string | null;
          role?: Database["public"]["Enums"]["participant_role"];
          status?: Database["public"]["Enums"]["registration_status"];
          source?: Database["public"]["Enums"]["registration_source"];
          is_captain?: boolean;
          waitlist_position?: number | null;
          registered_at?: string;
          confirmed_at?: string | null;
          cancelled_at?: string | null;
          cancellation_reason?: string | null;
          cancelled_by?: string | null;
          checked_in_at?: string | null;
          notes?: string | null;
          created_by?: string | null;
          updated_at?: string;
        };
        Update: {
          id?: string;
          event_id?: string;
          user_id?: string | null;
          team_id?: string | null;
          participant_name?: string;
          participant_email?: string | null;
          participant_phone?: string | null;
          role?: Database["public"]["Enums"]["participant_role"];
          status?: Database["public"]["Enums"]["registration_status"];
          source?: Database["public"]["Enums"]["registration_source"];
          is_captain?: boolean;
          waitlist_position?: number | null;
          registered_at?: string;
          confirmed_at?: string | null;
          cancelled_at?: string | null;
          cancellation_reason?: string | null;
          cancelled_by?: string | null;
          checked_in_at?: string | null;
          notes?: string | null;
          created_by?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "registrations_cancelled_by_fkey";
            columns: ["cancelled_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "registrations_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "registrations_event_id_fkey";
            columns: ["event_id"];
            isOneToOne: false;
            referencedRelation: "events";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "registrations_team_id_fkey";
            columns: ["team_id"];
            isOneToOne: false;
            referencedRelation: "teams";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "registrations_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      sport_formats: {
        Row: {
          id: string;
          sport_id: string;
          slug: string;
          name: string;
          registration_model: Database["public"]["Enums"]["registration_model"];
          default_team_size: number | null;
          default_substitutes: number;
          is_active: boolean;
          sort_order: number;
        };
        Insert: {
          id?: string;
          sport_id: string;
          slug: string;
          name: string;
          registration_model?: Database["public"]["Enums"]["registration_model"];
          default_team_size?: number | null;
          default_substitutes?: number;
          is_active?: boolean;
          sort_order?: number;
        };
        Update: {
          id?: string;
          sport_id?: string;
          slug?: string;
          name?: string;
          registration_model?: Database["public"]["Enums"]["registration_model"];
          default_team_size?: number | null;
          default_substitutes?: number;
          is_active?: boolean;
          sort_order?: number;
        };
        Relationships: [
          {
            foreignKeyName: "sport_formats_sport_id_fkey";
            columns: ["sport_id"];
            isOneToOne: false;
            referencedRelation: "sports";
            referencedColumns: ["id"];
          },
        ];
      };
      sports: {
        Row: {
          id: string;
          slug: string;
          name: string;
          cover_url: string | null;
          is_active: boolean;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          cover_url?: string | null;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          cover_url?: string | null;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      teams: {
        Row: {
          id: string;
          event_id: string;
          name: string;
          notes: string | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          event_id: string;
          name: string;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          event_id?: string;
          name?: string;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "teams_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "teams_event_id_fkey";
            columns: ["event_id"];
            isOneToOne: false;
            referencedRelation: "events";
            referencedColumns: ["id"];
          },
        ];
      };
      venues: {
        Row: {
          id: string;
          name: string;
          address: string | null;
          city: string;
          country: string;
          latitude: number | null;
          longitude: number | null;
          is_claimed: boolean;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          address?: string | null;
          city?: string;
          country?: string;
          latitude?: number | null;
          longitude?: number | null;
          is_claimed?: boolean;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          address?: string | null;
          city?: string;
          country?: string;
          latitude?: number | null;
          longitude?: number | null;
          is_claimed?: boolean;
          created_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "venues_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: { [_ in never]: never };
    Functions: { [_ in never]: never };
    Enums: {
      account_status: "active" | "inactive" | "suspended";
      event_status: "draft" | "submitted" | "under_review" | "changes_requested" | "approved" | "published" | "registration_open" | "registration_closed" | "completed" | "archived" | "rejected" | "cancelled" | "suspended" | "sold_out";
      fee_mode: "none" | "fixed" | "percentage" | "fixed_plus_percentage";
      gender_requirement: "any" | "male" | "female" | "mixed";
      message_audience: "all" | "confirmed" | "waitlisted" | "unpaid";
      participant_role: "player" | "captain" | "substitute";
      payment_method: "bank_transfer" | "cash_at_venue" | "online" | "comp";
      payment_status: "pending" | "processing" | "paid" | "failed" | "cancelled" | "refunded" | "partially_refunded";
      question_type: "text" | "number" | "dropdown" | "multiple_choice" | "checkbox" | "date" | "file";
      refund_status: "requested" | "approved" | "processing" | "refunded" | "declined";
      refund_type: "full" | "partial" | "credit" | "transfer" | "none";
      registration_model: "individual" | "team";
      registration_source: "online" | "admin";
      registration_status: "pending" | "confirmed" | "waitlisted" | "cancelled" | "no_show";
      user_role: "consumer" | "event_admin" | "super_admin";
    };
    CompositeTypes: { [_ in never]: never };
  };
};

type PublicSchema = Database["public"];
export type Tables<T extends keyof PublicSchema["Tables"]> =
  PublicSchema["Tables"][T]["Row"];
export type TablesInsert<T extends keyof PublicSchema["Tables"]> =
  PublicSchema["Tables"][T]["Insert"];
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> =
  PublicSchema["Tables"][T]["Update"];
export type Enums<T extends keyof PublicSchema["Enums"]> =
  PublicSchema["Enums"][T];
